#debug or release


[app]
PageSize  = 2
JwtSecret  = 23347$040412

[log]
LogFilePath = runtime/log
LogFileName = system
# 日志级别: trace, debug, info, warn, error, fatal, panic
LogLevel = info
# 日志格式: json, text
LogFormat = json
# 日志文件最大保存天数
LogMaxAge = 7
# 日志文件切割时间间隔(小时)
LogRotationTime = 24

[server]
RunMode  = debug
HttpPort = 8000
ReadTimeout = 60
WriteTimeout = 60

[database]
Type = mysql
User = thinkgin
Password = thinkgin
#127.0.0.1:3306
Host = 127.0.0.1:3306
Name = thinkgin
TablePrefix = tg_
