#debug or release


[app]
PageSize  = 2
JwtSecret  = 23347$040412

[log]
LogFilePath = runtime/log
LogFileName = system

[server]
RunMode  = debug
HttpPort = 8000
ReadTimeout = 60
WriteTimeout = 60

[database]
Type = mysql
User = thinkgin
Password = thinkgin
#127.0.0.1:3306
Host = 127.0.0.1:3306
Name = thinkgin
TablePrefix = tg_
