# 应用配置
app:
  name: "ThinkGin"
  version: "3.10.3"
  debug: true
  timezone: "Asia/Shanghai"
  locale: "zh-CN"

  # JWT 配置
  jwt:
    secret: "23347$040412"
    expire: 7200 # 2小时，单位秒

  # 分页配置
  pagination:
    page_size: 20
    max_page_size: 100

  # 监控配置
  monitoring:
    # 普罗米修斯监控总开关
    prometheus_enabled: true
