#debug or release
RUN_MODE = debug

[app]
PAGE_SIZE = 2
JWT_SECRET = 23347$040412

[log]
LOG_FILE_PATH = runtime/log
LOG_FILE_NAME = system

[server]
HTTP_PORT = 8000
READ_TIMEOUT = 60
WRITE_TIMEOUT = 60

[database]
TYPE = mysql
USER = go2022
PASSWORD = go2022
#127.0.0.1:3306
HOST = 127.0.0.1:3306
NAME = go2022
TABLE_PREFIX = blog_